site_name: 央央's Notebook
site_url: https://melody12020831.github.io/Notebook/
repo_name: Melody
repo_url: https://github.com/Melody12020831/Notebook/
site_description: 央央的笔记本
copyright: Copyright &copy; 2024 <a href="https://github.com/Melody12020831" target="_blank" rel="noopener">Melody</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  favicon: assets/images/icon.jpg

  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  # - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Melody12020831/
  analytics:
    provider: google
    property: G-002T22X4FB

extra_css:
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - css/custom.css
    - css/card.css
    - css/tasklist.css
    - css/flink.css
    - css/more_changelog.css
    - css/neoteroi-mkdocs.css
    - css/fold_toc.css
    - css/sidebar.css

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
    # - css/Javascripts/mathjax.js
    # - css/Javascripts/katex.js
    # Table Sort
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - css/javascripts/tablesort.js


plugins:
  # - rss
  - search:
      lang:
        - zh
        - en
      separator: '[\s\-\.]+'
  - glightbox
  #     width: 80%
  # - changelog
  # - heti
  # - tikzautomata
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      exclude:
        - index.md
  - statistics:
      words_per_minute: 200

nav:
  - Home: 
    - index.md
  - Computer Science:
    - Computer_Science/index.md
    - "ADS":
      - Computer_Science/ADS/index.md
      - Computer_Science/ADS/Homework.md
      - Computer_Science/ADS/organisedproblems.md
    - "CO":
      - Computer_Science/CO/index.md
      - Computer_Science/CO/Chapter 1.md
      - Computer_Science/CO/Chapter 2.md
      - Computer_Science/CO/Chapter 3.md
      - Computer_Science/CO/Chapter 4.md
      - Computer_Science/CO/Chapter 5.md
      - Computer_Science/CO/Chapter 6.md
      - Computer_Science/CO/COhomework.md
      - Computer_Science/CO/PPT_download.md
    - "DB":
      - Computer_Science/DB/index.md
      - Computer_Science/DB/Chapter1.md
      - Computer_Science/DB/Chapter2.md
      - Computer_Science/DB/Chapter3.md
      - Computer_Science/DB/Chapter4.md
      - Computer_Science/DB/Chapter5.md
      - Computer_Science/DB/Chapter6.md
      - Computer_Science/DB/Chapter7.md
      - Computer_Science/DB/Chapter8.md
      - Computer_Science/DB/Chapter12.md
      - Computer_Science/DB/Chapter13.md
      - Computer_Science/DB/Chapter14.md
      - Computer_Science/DB/Chapter15.md
      - Computer_Science/DB/Chapter16.md
      - Computer_Science/DB/Chapter17.md
      - Computer_Science/DB/Chapter18.md
      - Computer_Science/DB/Chapter19.md
      - Computer_Science/DB/homework.md
      - Computer_Science/DB/sql.md
    - "OOP":
      - Computer_Science/OOP/index.md
      - Computer_Science/OOP/Chapter1.md
      - Computer_Science/OOP/Chapter2.md
      - Computer_Science/OOP/Chapter3.md
      - Computer_Science/OOP/Chapter4.md
      - Computer_Science/OOP/Chapter5.md
      - Computer_Science/OOP/Chapter6.md
      - Computer_Science/OOP/Chapter7.md
      - Computer_Science/OOP/Chapter8.md
      - Computer_Science/OOP/Chapter9.md
      - Computer_Science/OOP/Chapter10.md
      - Computer_Science/OOP/Chapter11.md
      - Computer_Science/OOP/Chapter12.md
      - Computer_Science/OOP/Chapter13.md
      - Computer_Science/OOP/Chapter14.md
      - Computer_Science/OOP/Chapter15.md
      - Computer_Science/OOP/homework.md
      - Computer_Science/OOP/test_from_wk.md
      - Computer_Science/OOP/105_STL_Algorithmsin_Less_Than_an_Hour.md
    - "CA":
      - Computer_Science/CA/index.md
      - Computer_Science/CA/Chapter1.md
      - Computer_Science/CA/Chapter2.md
      - Computer_Science/CA/homework.md
      - Computer_Science/CA/CA_review.md
    - "TOC":
      - Computer_Science/TOC/index.md
      - Computer_Science/TOC/Chapter1.md
      - Computer_Science/TOC/Chapter2.md
      - Computer_Science/TOC/Chapter3.md
    - "OS":
      - Computer_Science/OS/index.md
      - Computer_Science/OS/Chapter1.md
      - Computer_Science/OS/Chapter2.md
      - Computer_Science/OS/Chapter3.md
      - Computer_Science/OS/Chapter4.md
      - Computer_Science/OS/Chapter5.md
      - Computer_Science/OS/Chapter8.md
    - "CN":
      - Computer_Science/CN/index.md
      - Computer_Science/CN/Chapter1.md
      - Computer_Science/CN/Chapter2.md
      - Computer_Science/CN/Chapter3.md
      - Computer_Science/CN/quiz.md
    - "Visualization":
      - Computer_Science/Visualization/note.md
    - "编程语言":
      - Computer_Science/Programming_Language/python/CS50P_python.md
      - Computer_Science/Programming_Language/python/python100days.md
    - "Tools":
      - Computer_Science/Tools/Git.md
      - Computer_Science/Tools/reveal-md.md
  - Math: 
    - Math/index.md
    - "概率论与数理统计":
        - Math/Probability_Theory_and_Mathematical_Statistics/index.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter1.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter2.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter3.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter4.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter5.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter6.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter7.md
        - Math/Probability_Theory_and_Mathematical_Statistics/Chapter8.md
        - Math/Probability_Theory_and_Mathematical_Statistics/PPT_download.md
        - "Homework":
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/Homework_index.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW1.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW2.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW3.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW4.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW5.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW6.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW7.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW8.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW9.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW10.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW11.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW12.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW13.md
          - Math/Probability_Theory_and_Mathematical_Statistics/HW/HW14.md
  - Misccelleanous:
    - Miscellaneous/index.md
    - Miscellaneous/prompt/prompt.md
    - Miscellaneous/mermaid.md
    - "UBC":
      - Miscellaneous/UBC/block chain DAY 1.md
      - Miscellaneous/UBC/block chain DAY 2.md
      - Miscellaneous/UBC/block chain DAY 3.md
      - Miscellaneous/UBC/block chain DAY 4.md
      - Miscellaneous/UBC/block chain DAY 5.md
      - Miscellaneous/UBC/block chain DAY 6.md
      - Miscellaneous/UBC/block chain DAY 7.md
      - Miscellaneous/UBC/block chain DAY 8.md
    - Miscellaneous/cs231n/note.md